export const actionTypes = {
    SET_USER : 'SET_USER',
    SET_ADMIN : 'SET_ADMIN',
    REMOVE_USER : 'REMOVE_USER',
    REMOVE_ADMIN : 'REMOVE_ADMIN',
    FETSH_ALL_JOBS : 'FETSH_ALL_JOBS',
    FETCH_JOBS : 'FETCH_JOBS',
    REVOME_JOBS : 'REVOME_JOBS'
};